### PR TITLE
Added notebook showing # versions vs. file size for fixed array size

### PR DESCRIPTION
**Pull request by melissawm**
More coming soon.

### CODE REVIEW

**Comment by asmeurer** [comment]
Should we check in the plots with the notebooks? @scopatz what do you think?

**Comment by scopatz** [comment]
It is nice to have the plots when they are "done", so that it is easy for people to see the results. But there will be churn during development, so that is less great.  I think for the momement having no plots is probably better

**Comment by scopatz** [comment]
@melissawm - please remove spaces from file names :wink: Thanks!

**Comment by melissawm** [comment]
Done. Sorry!

**Comment by melissawm** [comment]
I'll close this PR and open a new one since the notebook has changed significantly since it was first submitted.

**Pull request closed without merging**
