### PR TITLE
Add InMemoryArrayDataset

### PR DESCRIPTION
**Pull request by asmeurer**
This is used when the dataset is created from an array. That way, we don't
have to create a fake Dataset on the file so that we can use InMemoryDataset.

### CODE REVIEW

**Comment by asmeurer** [comment]
This still needs more tests.

**Comment by scopatz** [comment]
Implementation looks fine, at this point

**Comment by asmeurer** [comment]
This now adds support for attrs. For now they are just represented in the API as a dictionary. If we need to, we can make a wrapper so they act more like the h5py AttributeManager object. One effect of this is that the type checking on attrs won't happen until the version is committed (this sort of thing, where errors only happen when the version is committed, happens in some other places as well).

**Comment by ArvidJB** [comment]
Looks good, I just tried those changes and they seem to fix the issues I had!
👍

**Comment by scopatz** [comment]
Thank @asmeurer!

**Pull request merged**
