### PR TITLE
support for resizing datasets

### LINKED ISSUE #16: Resize support

### PR DESCRIPTION
**Pull request by asmeurer**
- It doesn't yet support resizing datasets that aren't multiples of the
  chunk size.
- It still needs tests.

Fixes #16.

### CODE REVIEW

**Comment by scopatz** [comment]
It looks like travis never ran

**Comment by scopatz** [comment]
Implementation looks fine to me, but please add some tests :wink:

**Comment by asmeurer** [comment]
Weird, it looks like it ran https://travis-ci.org/github/Quansight/versioned-hdf5/builds/666546349. It just didn't report it back to GitHub for some reason.

**Comment by asmeurer** [comment]
This is ready to go. There is one line that isn't covered in the tests, but I can't fix that until I fix #22 (but the line should be correct, I just can't test it yet).

**Pull request merged**
